### ISSUE TITLE
Try out odoo-saas-tools

### ISSUE THREAD

**Issue by bitsnaps** [PixelDima/suggestions#1]
Salam Adel,

Have you tried [odoo-saas-tools](https://github.com/it-projects-llc/odoo-saas-tools/) kit? basically, it's a set of tools that allows you to auto-deploy and manage odoo instance, fully-featured and ready for starting a business, it's been for years with many improvements, not really easy to deploy though, let me know if you're interested so we can share and join our work together.

Regards

**Comment by AdelDima** [comment]
Hello, thanks for your visit, actually I did not test it before,
Please feel free to send us an email contact [@]devodoo[.]come
